CREATE SCHEMA "talk_tracker";
--> statement-breakpoint
CREATE TABLE "talk_tracker"."account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."activity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proposal_id" integer,
	"event_id" integer,
	"talk_id" integer,
	"user_id" text NOT NULL,
	"activity_type" text NOT NULL,
	"content" text,
	"is_edited" boolean DEFAULT false NOT NULL,
	"edited_at" timestamp with time zone,
	"old_status" text,
	"new_status" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."app_setting" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."app_setting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"value" text NOT NULL,
	"description" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "app_setting_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."event_participation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."event_participation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_id" integer NOT NULL,
	"participation_type" text NOT NULL,
	"status" text DEFAULT 'interested' NOT NULL,
	"budget" integer,
	"sponsorship_tier" text,
	"booth_size" text,
	"details" text,
	"notes" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."event_score" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."event_score_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_id" integer NOT NULL,
	"category_id" integer NOT NULL,
	"score" integer NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"start_date" date,
	"end_date" date,
	"location" text,
	"description" text,
	"cfp_deadline" date,
	"cfp_url" text,
	"conference_website" text,
	"notes" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."mention" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."mention_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"activity_id" integer NOT NULL,
	"mentioned_user_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."notification_preference" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."notification_preference_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"mentions_enabled" boolean DEFAULT true NOT NULL,
	"status_changes_enabled" boolean DEFAULT true NOT NULL,
	"comments_enabled" boolean DEFAULT true NOT NULL,
	"cfp_deadlines_enabled" boolean DEFAULT true NOT NULL,
	"cfp_deadline_days_before" integer DEFAULT 7 NOT NULL,
	"email_mentions_enabled" boolean DEFAULT false NOT NULL,
	"email_status_changes_enabled" boolean DEFAULT false NOT NULL,
	"email_comments_enabled" boolean DEFAULT false NOT NULL,
	"email_cfp_deadlines_enabled" boolean DEFAULT false NOT NULL,
	"slack_mentions_enabled" boolean DEFAULT false NOT NULL,
	"slack_status_changes_enabled" boolean DEFAULT false NOT NULL,
	"slack_comments_enabled" boolean DEFAULT false NOT NULL,
	"slack_cfp_deadlines_enabled" boolean DEFAULT false NOT NULL,
	"slack_webhook_url" text,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "notification_preference_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"notification_type" text NOT NULL,
	"activity_id" integer,
	"event_id" integer,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"link_url" text NOT NULL,
	"actor_id" text,
	"is_read" boolean DEFAULT false NOT NULL,
	"read_at" timestamp with time zone,
	"delivery_method" text DEFAULT 'in_app' NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."proposal" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."proposal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"talk_id" integer NOT NULL,
	"event_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"talk_type" text NOT NULL,
	"submission_date" date,
	"notes" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."scoring_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."scoring_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"weight" integer NOT NULL,
	"display_order" integer NOT NULL,
	"score_9_description" text NOT NULL,
	"score_3_description" text NOT NULL,
	"score_1_description" text NOT NULL,
	"score_0_description" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "scoring_category_weight_unique" UNIQUE("weight")
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."talk_tag_assignment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."talk_tag_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"talk_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."talk_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."talk_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"color" text,
	"description" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "talk_tag_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."talk" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talk_tracker"."talk_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"abstract" text NOT NULL,
	"description" text,
	"created_by_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "talk_tracker"."verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "talk_tracker"."account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "talk_tracker"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."activity" ADD CONSTRAINT "activity_proposal_id_proposal_id_fk" FOREIGN KEY ("proposal_id") REFERENCES "talk_tracker"."proposal"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."activity" ADD CONSTRAINT "activity_event_id_event_id_fk" FOREIGN KEY ("event_id") REFERENCES "talk_tracker"."event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."activity" ADD CONSTRAINT "activity_talk_id_talk_id_fk" FOREIGN KEY ("talk_id") REFERENCES "talk_tracker"."talk"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."activity" ADD CONSTRAINT "activity_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "talk_tracker"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."event_participation" ADD CONSTRAINT "event_participation_event_id_event_id_fk" FOREIGN KEY ("event_id") REFERENCES "talk_tracker"."event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."event_score" ADD CONSTRAINT "event_score_event_id_event_id_fk" FOREIGN KEY ("event_id") REFERENCES "talk_tracker"."event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."event_score" ADD CONSTRAINT "event_score_category_id_scoring_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "talk_tracker"."scoring_category"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."mention" ADD CONSTRAINT "mention_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "talk_tracker"."activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."mention" ADD CONSTRAINT "mention_mentioned_user_id_user_id_fk" FOREIGN KEY ("mentioned_user_id") REFERENCES "talk_tracker"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."notification_preference" ADD CONSTRAINT "notification_preference_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "talk_tracker"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."notification" ADD CONSTRAINT "notification_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "talk_tracker"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."notification" ADD CONSTRAINT "notification_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "talk_tracker"."activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."notification" ADD CONSTRAINT "notification_event_id_event_id_fk" FOREIGN KEY ("event_id") REFERENCES "talk_tracker"."event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."notification" ADD CONSTRAINT "notification_actor_id_user_id_fk" FOREIGN KEY ("actor_id") REFERENCES "talk_tracker"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."proposal" ADD CONSTRAINT "proposal_talk_id_talk_id_fk" FOREIGN KEY ("talk_id") REFERENCES "talk_tracker"."talk"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."proposal" ADD CONSTRAINT "proposal_event_id_event_id_fk" FOREIGN KEY ("event_id") REFERENCES "talk_tracker"."event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."proposal" ADD CONSTRAINT "proposal_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "talk_tracker"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "talk_tracker"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."talk_tag_assignment" ADD CONSTRAINT "talk_tag_assignment_talk_id_talk_id_fk" FOREIGN KEY ("talk_id") REFERENCES "talk_tracker"."talk"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."talk_tag_assignment" ADD CONSTRAINT "talk_tag_assignment_tag_id_talk_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "talk_tracker"."talk_tag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "talk_tracker"."talk" ADD CONSTRAINT "talk_created_by_id_user_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "talk_tracker"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "activity_proposal_idx" ON "talk_tracker"."activity" USING btree ("proposal_id");--> statement-breakpoint
CREATE INDEX "activity_event_idx" ON "talk_tracker"."activity" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "activity_talk_idx" ON "talk_tracker"."activity" USING btree ("talk_id");--> statement-breakpoint
CREATE INDEX "activity_user_idx" ON "talk_tracker"."activity" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "activity_type_idx" ON "talk_tracker"."activity" USING btree ("activity_type");--> statement-breakpoint
CREATE INDEX "activity_created_idx" ON "talk_tracker"."activity" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "app_setting_key_idx" ON "talk_tracker"."app_setting" USING btree ("key");--> statement-breakpoint
CREATE INDEX "event_participation_event_idx" ON "talk_tracker"."event_participation" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "event_participation_type_idx" ON "talk_tracker"."event_participation" USING btree ("participation_type");--> statement-breakpoint
CREATE INDEX "event_score_event_idx" ON "talk_tracker"."event_score" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "event_score_category_idx" ON "talk_tracker"."event_score" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "event_name_idx" ON "talk_tracker"."event" USING btree ("name");--> statement-breakpoint
CREATE INDEX "event_start_date_idx" ON "talk_tracker"."event" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "mention_activity_idx" ON "talk_tracker"."mention" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "mention_user_idx" ON "talk_tracker"."mention" USING btree ("mentioned_user_id");--> statement-breakpoint
CREATE INDEX "notification_preference_user_idx" ON "talk_tracker"."notification_preference" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "notification_user_idx" ON "talk_tracker"."notification" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "notification_read_idx" ON "talk_tracker"."notification" USING btree ("is_read");--> statement-breakpoint
CREATE INDEX "notification_type_idx" ON "talk_tracker"."notification" USING btree ("notification_type");--> statement-breakpoint
CREATE INDEX "notification_created_idx" ON "talk_tracker"."notification" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "notification_activity_idx" ON "talk_tracker"."notification" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "notification_event_idx" ON "talk_tracker"."notification" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "proposal_talk_idx" ON "talk_tracker"."proposal" USING btree ("talk_id");--> statement-breakpoint
CREATE INDEX "proposal_event_idx" ON "talk_tracker"."proposal" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "proposal_user_idx" ON "talk_tracker"."proposal" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "proposal_status_idx" ON "talk_tracker"."proposal" USING btree ("status");--> statement-breakpoint
CREATE INDEX "scoring_category_display_order_idx" ON "talk_tracker"."scoring_category" USING btree ("display_order");--> statement-breakpoint
CREATE INDEX "talk_tag_assignment_talk_idx" ON "talk_tracker"."talk_tag_assignment" USING btree ("talk_id");--> statement-breakpoint
CREATE INDEX "talk_tag_assignment_tag_idx" ON "talk_tracker"."talk_tag_assignment" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "talk_tag_name_idx" ON "talk_tracker"."talk_tag" USING btree ("name");--> statement-breakpoint
CREATE INDEX "talk_created_by_idx" ON "talk_tracker"."talk" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX "talk_title_idx" ON "talk_tracker"."talk" USING btree ("title");